apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-hello
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wiktorvip/app-hello
    path: manifest
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: app-hello

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
