apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-webcolor
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wiktorvip/app-webcolor
    targetRevision: HEAD
    path: manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: app-webcolor

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
