apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wiktorvip/manifest-app-demo
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: appdemo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
