apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-color
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wiktorvip/webapp-color-manifest
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: webapp-color

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
